"""Provider ingestion primitives."""

from arbiscan.ingestion.collector import (
    IngestedSnapshot,
    IngestionBatch,
    IngestionIssue,
    collect_snapshots,
)
from arbiscan.ingestion.multisource import (
    MultiSourceQuoteStore,
    PriceSlotKey,
    QuoteConsolidationDiagnostic,
    QuoteConsolidationDiagnosticCode,
    QuoteConsolidationResult,
    SourceQuoteKey,
    SourceQuoteStoreApplyResult,
    SourceQuoteStoreDiagnostic,
    SourceQuoteStoreDiagnosticCode,
    SourceQuoteStoreEvictionResult,
    SourceQuoteVersion,
)
from arbiscan.ingestion.realtime import (
    LiveQuoteStore,
    ProviderIngestionHealth,
    ProviderPollMetrics,
    ProviderRateGate,
    QuoteKey,
    QuoteStoreApplyResult,
    QuoteStoreDiagnostic,
    QuoteStoreDiagnosticCode,
    QuoteStoreEvictionResult,
    QuoteVersion,
    RealtimeIngestionBatch,
    RealtimeIngestionPolicy,
    RealtimeIngestionRuntime,
)

__all__ = [
    "IngestedSnapshot",
    "IngestionBatch",
    "IngestionIssue",
    "LiveQuoteStore",
    "MultiSourceQuoteStore",
    "PriceSlotKey",
    "ProviderIngestionHealth",
    "ProviderPollMetrics",
    "ProviderRateGate",
    "QuoteConsolidationDiagnostic",
    "QuoteConsolidationDiagnosticCode",
    "QuoteConsolidationResult",
    "QuoteKey",
    "QuoteStoreApplyResult",
    "QuoteStoreDiagnostic",
    "QuoteStoreDiagnosticCode",
    "QuoteStoreEvictionResult",
    "QuoteVersion",
    "RealtimeIngestionBatch",
    "RealtimeIngestionPolicy",
    "RealtimeIngestionRuntime",
    "SourceQuoteKey",
    "SourceQuoteStoreApplyResult",
    "SourceQuoteStoreDiagnostic",
    "SourceQuoteStoreDiagnosticCode",
    "SourceQuoteStoreEvictionResult",
    "SourceQuoteVersion",
    "collect_snapshots",
]
